version: 2
jobs:
  prepare_deploy:
    docker:
      - image: eklhad/terrasnek-circleci:0.4
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Lint the code, build the docs, run a full test suite and the contributor check.
          command: |
            make lint
            make docs
            make coverage
            make contributor_check
  api_comparison:
    docker:
      - image: eklhad/terrasnek-circleci:0.4
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Compare API docs against implemented endpoints, identify gaps.
          command: |
            make api_comparison
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - prepare_deploy
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  check_api_completeness:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - api_comparison