version: 2
jobs:
  contributor_check:
    docker:
      - image: eklhad/terrasnek-circleci:0.6
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Lint the code, build the docs, run a full test suite and the contributor check.
          command: |
            make lint
            make docs
            make coverage
            make contributor_check
  coverage:
    docker:
      - image: eklhad/terrasnek-circleci:0.6
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Run the full test suite.
          command: |
            make coverage
  api_comparison:
    docker:
      - image: eklhad/terrasnek-circleci:0.6
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: Compare API docs against implemented endpoints, identify gaps.
          command: |
            make api_comparison
workflows:
  version: 2
  contributor_check:
    jobs:
      - contributor_check
  coverage:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - coverage
  api_completeness_check:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - api_comparison